name = "Optimized Reclaim View"
version = 1
copyright = ""
description = "No more 0 FPS when reclaim is displayed"
author = "4z0t"
url = ""
uid = "optimized-reclaim-view-v01"
icon = "/mods/ORV/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
