name = "Factory Queue Functions"
version = 1
copyright = ""
description = ""
author = "4z0t"
url = ""
uid = "your-mod-uid"
icon = "/mods/FQF/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
