name = "Amphibians"
uid = "amphibian-icons-4z0t-v01"
version = 1
copyright = ""
icon = "/mods/Amphibians/icon.png"
description = "Adds amphibians icons for Wagner, Blaze, Riptide and Yenzyne"
author = "4z0t"
selectable = true
enabled = true
exclusive = false
ui_only = true
