name = "Rings For All"
uid = "rings-for-all-v01"
version = 1
copyright = ""
description = [[]]
author = "4z0t"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
